#!/bin/bash


folders=$(ls -d ./project/*/ 2>/dev/null)

if [ -z "$folders" ]; then
    echo "
No Databases Found
"
else

    folder_names=$(echo "$folders" | sed 's:^./project/::' | sed 's:/$::')
    echo "
Available databases:"
    echo "$folder_names
"
fi
